# Use the official image as a parent image.
FROM tensorflow/tensorflow:1.15.2

# Set the working directory.
WORKDIR /usr/src/hlc_evaluator

# Run the command inside your image filesystem.
RUN pip install tcav torch tqdm
